# Generated by Django 4.2.21 on 2026-06-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_useraddress_label'),
        ('users', '0002_alter_user_options_alter_useraddress_options_and_more'),
    ]

    operations = [
    ]
