# Generated by Django 4.2.21 on 2026-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20260609_1837"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Set to True after the user clicks the verification link.",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
