# Generated by Django 4.2.21 on 2026-06-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260609_1214'),
        ('users', '0004_add_is_email_verified'),
    ]

    operations = [
    ]
