# Generated by Django 4.2.21 on 2026-06-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created_at", "id"]},
        ),
    ]
