# Generated by Django 4.2.21 on 2026-06-15 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="helpful_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who found this review helpful",
                related_name="helpful_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
