# Generated by Django 4.2.21 on 2026-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_scheduledmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmessage",
            name="body",
            field=models.TextField(
                help_text="Supports tokens: {{first_name}}, {{last_name}}, {{full_name}}, {{email}}, {{role}}. If no name token is present, a personalized greeting is prepended automatically."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledmessage",
            name="subject",
            field=models.CharField(
                help_text="Supports tokens: {{first_name}}, {{last_name}}, {{full_name}}, {{email}}, {{role}}",
                max_length=255,
            ),
        ),
    ]
